apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod

components:
  - ../../../components/argocd-hook

configMapGenerator:
  - name: hook-config
    behavior: merge
    literals:
      - ENVIRONMENT=prod
