apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example-app-staging

commonLabels:
  environment: staging

resources:
- ../../base

images:
  - name: quay.io/gh-stocky37/greeting-api
    newTag: staging

