apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-gitops
resources:
  - ../../util/argocd-hook/overlays/postsync
components:
  - ../../components/postsync-hook/webhook-url
