apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../variants/dev

patches:
- path: patch-route.yml

configMapGenerator:
- behavior: merge
  literals:
  - WEBHOOK_URL=http://webhooks-demo-gitops-cicd-cicd.apps.cluster-z2575.z2575.sandbox2802.opentlc.com/
  name: hook-config
images:
- digest: sha256:2b82bd50535486fde81a7da944234a2e1f70bb95a5213c60c16f82a0c09352ea
  name: quay.io/tstockwell/greeting-api
