apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    environment: prod

resources:
- app
- postsync-hook

images:
- digest: sha256:5bb61f4c85a9ef22fc609ffe88034dceda738af889831e5f06222f68af0e1143
  name: quay.io/rh-hcas-emea/greeting-ui
