apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    environment: prod

resources:
- app
- postsync-hook

images:
- digest: sha256:8cef79cf09bfa0f6363cca0329a30aa0a57a9634ca65fe26b2a49de9f336d7af
  name: quay.io/rh-hcas-emea/greeting-ui
