apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: &app greeting-db
      app.kubernetes.io/name: *app
      app.kubernetes.io/instance: *app
      app.kubernetes.io/component: database
      app.openshift.io/runtime: postgresql
      app.kubernetes.io/part-of: greeting-app

resources:
  - deployment.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
