apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name greeting-api
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: *name
  template:
    metadata:
      labels:
        deployment: *name
    spec:
      containers:
      - name: app
        image: quay.io/rh-hcas-emea/greeting-api:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        env: []
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: &port 8080
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: *port
        startupProbe:
          httpGet:
            path: /q/health/started
            port: *port
