apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    environment: prod

resources:
- app
- argocd-hook

images:
- digest: sha256:a1fdc864a2b0c7cc049b303f2d3aa90589ff70f7c8eefd6afe0f6c2c876c76c9
  name: quay.io/rh-hcas-emea/greeting-api
