apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: &app greeting-db
  app.kubernetes.io/name: *app
  app.kubernetes.io/instance: *app
  app.kubernetes.io/component: database
  app.openshift.io/runtime: postgresql


resources:
  - deployment.yml
  - persistentvolumeclaim.yml
  - secret.yml
  - service.yml
