apiVersion: v1
kind: Service
metadata:
  name: greeting-db
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deployment: greeting-db
  sessionAffinity: None
