apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    environment: stage

resources:
- app
- postsync-hook

images:
- digest: sha256:1711028d5431c473457bca9e5eaa964c27943390e25871b1e738dd38c0630b61
  name: quay.io/rh-hcas-emea/greeting-api
