apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: prod

resources:
- app
- argocd

images:
- digest: sha256:6d85abab3e16512242d5120e1c4e32c97e429bb0e67a57c2e1b6f617d8af47c0
  name: quay.io/tstockwell/greeting-api
