apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-gitops
nameSuffix: -dev

resources:
  - ../../../components/argocd-hook

configMapGenerator:
  - name: hook-config
    behavior: merge
    literals:
      - ENVIRONMENT=dev

