apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example-app-development

commonLabels:
  environment: development

resources:
- ../../base

images:
- digest: sha256:c0f10db5a97a951907dcb13afb687d846de4cf0a877857f371b57174fca94063
  name: quay.io/gh-stocky37/greeting-api


replacements:
- source:
    fieldPath: metadata.labels.environment
    kind: Route
  targets:
  - fieldPaths:
    - spec.host
    options:
      delimiter: .
      index: -1
    select:
      kind: Route
