apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    environment: dev

resources:
- app
- postsync-hook

images:
- digest: sha256:9b8f75191d4c18df658507ece56043a7aef96cd1b28d5fc575d11223be910f7c
  name: quay.io/rh-hcas-emea/greeting-ui
