apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    environment: dev

resources:
- app
- postsync-hook

images:
- digest: sha256:9b186a63c9e63a8994794089897ff6c358a47e090dca1bf79069695be88018a8
  name: quay.io/rh-hcas-emea/greeting-ui
