apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-api
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: greeting-api
  template:
    metadata:
      labels:
        deployment: greeting-api
    spec:
      containers:
      - name: greeting-api
        image: quay.io/gh-stocky37/greeting-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              key: database-name
              name: greeting-db
        - name: QUARKUS_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: greeting-db
        - name: QUARKUS_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: greeting-db
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
