apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: greeting-api
  annotations:
    openshift.io/host.generated: 'true'
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: ratings
    weight: 100
  wildcardPolicy: None
