apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: greeting-api
spec:
  host: api.example-app.apps.paas.lab.stocky37.dev
  port:
    targetPort: 8080
  to:
    kind: Service
    name: greeting-api
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
