apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: stage

resources:
- app
- argocd

images:
- digest: sha256:78dd730076b7d1c576e31f762488ef70b62bf6aff86297fbcbc750645d884e4c
  name: quay.io/tstockwell/greeting-api
