apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  app.openshift.io/vcs-uri: https://github.com/tom-stockwell/greeting-api.git

commonLabels:
  app: &app greeting-api
  app.kubernetes.io/name: *app
  app.kubernetes.io/instance: *app
  app.kubernetes.io/component: backend
  app.openshift.io/runtime: quarkus

resources:
  - deployment.yml
  - route.yml
  - service.yml
