apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/greeting-api/overlays/default
components:
  - ../../../../components/namespace-prod
patches:
  - path: patch-deployment.yml
