apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/greeting-ui/overlays/default

components:
  - ../../../../components/namespace-stage

configMapGenerator:
  - name: greeting-ui-config
    behavior: merge
    files:
      - files/env.js
